### ISSUE TITLE
Providing session and user id manually for ruby

### ISSUE THREAD

**Issue by ghost** [jvenezia/tinderbot#11]
How can I specify manually my session ID as well as user ID for rubby script instead of using automatic one which fails on linux.

**Comment by jvenezia** [comment]
Hi @ment0s , yes you can do that : 
`tinder_client.sign_in [facebook_authentication_token, facebook_user_id]`

What exactly is not working on linux?

**Comment by jvenezia** [comment]
@ment0s Feel free to reopen if needed.
