### ISSUE TITLE
`block in initialize_http_head er': undefined method `strip' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by frenton** [jvenezia/tinderbot#7]
Executing this code:

"require 'tinderbot'

facebook_authentication_token = '.........' 
facebook_user_id = '........'

tinder_client = Tinderbot::Client.new
tinder_authentication_token = tinder_client.get_authentication_token facebook_authentication_token, facebook_user_id
tinder_client.sign_in tinder_authentication_token

tinder_client.update_location '40.7313029,-73.9884189'"

I am getting this error:

"C:/Ruby21/lib/ruby/2.1.0/net/http/header.rb:17:in `block in initialize_http_head
er': undefined method `strip' for nil:NilClass (NoMethodError)
        from C:/Ruby21/lib/ruby/2.1.0/net/http/header.rb:15:in `each'
        from C:/Ruby21/lib/ruby/2.1.0/net/http/header.rb:15:in `initialize_http_
header'
        from C:/Ruby21/lib/ruby/2.1.0/net/http/generic_request.rb:44:in `initial
ize'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/adapte
r/net_http.rb:62:in `new'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/adapte
r/net_http.rb:62:in `create_request'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/adapte
r/net_http.rb:82:in `perform_request'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/adapte
r/net_http.rb:40:in `block in call'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/adapte
r/net_http.rb:87:in `with_net_http_connection'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/adapte
r/net_http.rb:32:in `call'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/faraday_middleware-0.9.1/lib/far
aday_middleware/request/encode_json.rb:23:in `call'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/rack_b
uilder.rb:139:in `build_response'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/connec
tion.rb:377:in `run_request'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/connec
tion.rb:177:in `post'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/tinderbot-0.0.12/lib/tinderbot/c
lient.rb:69:in `update_location'
        from do-tinder.rb:10:in `<main>'"

Can you guys help me??

**Comment by jvenezia** [comment]
Hey !

Does **tinder_authentication_token** seems valid ?

**Comment by frenton** [comment]
Yes, I tested several valid accounts. Always the same error.

**Comment by jvenezia** [comment]
Ok, I'll try this and come back to you.

**Comment by frenton** [comment]
Thanks!

**Comment by frenton** [comment]
UPDATE: It was an error in auth data. Works fine now. Thanks, though!
