### ISSUE TITLE
Auto facebook login broken.

### ISSUE THREAD

**Issue by jvenezia** [jvenezia/tinderbot#8]
Facebook login seems to be broken.
I'll check that.

**Comment by RossKinsella** [comment]
I have no issues with this.

**Comment by RossKinsella** [comment]
I did have an issue where facebook says something along the lines of 'You have tried to log in too often, come back later'.

Might be an idea to do a check for this message after clicking on the submit button:



    def self.get_credentials(facebook_email, facebook_password)
      browser = Watir::Browser.new
      browser.goto FACEBOOK_AUTHENTICATION_TOKEN_URL
      browser.text_field(id: 'email').when_present.set facebook_email
      browser.text_field(id: 'pass').when_present.set facebook_password
      browser.button(name: 'login').when_present.click

      if !browser. << HAS THE ERROR >>
        facebook_authentication_token = /#access_token=(.*)&expires_in/.match(browser.url).captures[0]
        browser.goto 'https://www.facebook.com/'
        browser.link(class: 'fbxWelcomeBoxName').when_present.click
        facebook_user_id = /fbid=(.*)&set/.match(browser.link(class: 'profilePicThumb').when_present.href).captures[0]
        browser.close
        return facebook_authentication_token
      else
         raise 'You need to pause your bot for a couple hours' 
      end
    end

**Comment by jvenezia** [comment]
It seems to work right now... Feel free to reopen...
