### ISSUE TITLE
Facebook login with headless browser

### ISSUE THREAD

**Issue by RossKinsella** [jvenezia/tinderbot#9]
I want to deploy an application onto a server which has no display.

Currently, the facebook login method fails in this scenario.
- I think PhantomJS might be a good solution but I have no experience with it.

Any suggestions?

**Comment by RossKinsella** [comment]
Would it also be possible to get a long term token as opposed to short?

**Comment by jvenezia** [comment]
@RossKinsella Yep why not, headless browser would be useful.
I think that the simplest solution would be to use https://github.com/leonid-shevtsov/headless .
But I would not work on OSX.

Feel free to give it a try and contribute!

For the long term token, I don't think it is possible. We are stucked with a short term token given by facebook. I don't know any workaround right now...

**Comment by RossKinsella** [comment]
I actually already implemented a solution using that gem and I'm pretty happy with the results.
-- I simply check to see if my tinder_client can still pull updates and if not, I run the initialiser again.

I see that the face app-id Tinderbot::Facebook.get_credentials uses is the literal tinder app id, so theres nothing we can do to get a long term token as we would need the secret key.

A possible hack might be to explore a smart phone's memory which has tinder installed for a long term token and see about harvesting that token, if it exists.

That level of hackery is beyond me, however.
